FROM php:7.3-apache
# Dependencies for dba extension
RUN apt-get update && apt-get install -y \
    liblmdb-dev \
  && docker-php-ext-configure dba --enable-dba --with-lmdb \
  && docker-php-ext-install dba \
  && a2enmod rewrite
# Override for Travis CI build
ENV CORN_DBA_PATH_OVERRIDE /tmp/
