version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-src
    ports:
    - "8000:80"
    volumes:
    - ./src:/var/www/html
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
    - SELENIUM_HOST=selenium
    - SELENIUM_PORT=4444
    - TARGET_HOST=web
    volumes:
    - ./test:/usr/src/test
    depends_on:
    - selenium
    - web
    entrypoint:
    - rspec
    - --require
    - ./spec_helper
    - --pattern
    - "spec/*_spec.rb"
    - --force-color
  selenium:
    image: selenium/standalone-firefox:3
